# permissions for end users to edit datastoreinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datastoreinfo-editor-role
rules:
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - datastoreinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - datastoreinfoes/status
  verbs:
  - get
