# permissions for end users to view datastoreinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datastoreinfo-viewer-role
rules:
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - datastoreinfoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - datastoreinfoes/status
  verbs:
  - get
