# permissions for end users to edit nodeinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeinfo-editor-role
rules:
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - nodeinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - nodeinfoes/status
  verbs:
  - get
