# permissions for end users to view nodeinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeinfo-viewer-role
rules:
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - nodeinfoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - nodeinfoes/status
  verbs:
  - get
