# permissions for end users to edit nodenetinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodenetinfo-editor-role
rules:
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - nodenetinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - nodenetinfoes/status
  verbs:
  - get
