# permissions for end users to view taginfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taginfo-viewer-role
rules:
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - taginfoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - taginfoes/status
  verbs:
  - get
