# permissions for end users to edit taginfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taginfo-editor-role
rules:
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - taginfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - taginfoes/status
  verbs:
  - get
